/** @type {import('stylelint').Config} */
export default {
    extends: ["stylelint-config-standard-scss"],
    plugins: ["stylelint-plugin-logical-css", "stylelint-scss"],
    rules: {
        "at-rule-no-unknown": null,
        "at-rule-empty-line-before": ["always", { "severity": "warning", "except": ["first-nested", "blockless-after-blockless"] }],
        "scss/at-rule-no-unknown": [true, {
            "ignoreAtRules": [
                "function",
                "mixin",
                "include",
                "extend",
                "use",
                "forward",
                "return",
                "if",
                "else",
                "for",
                "each",
                "while",
                "warn",
                "debug",
                "error",
                "layer",
                "property"
            ],
            "severity": "warning"
        }],
        "function-no-unknown": null,
        "scss/function-no-unknown": [true, {
            "ignoreFunctions": [
                "color-mix",
                "oklch",
                "oklab",
                "style"
            ],
            "severity": "warning"
        }],
        "selector-type-no-unknown": null,
        "block-no-empty": [true, { "severity": "warning" }],
        "comment-no-empty": [true, { "severity": "warning" }],
        "no-descending-specificity": null,
        "selector-class-pattern": null,
        "color-function-notation": ["modern", {"severity": "warning"}],
        "alpha-value-notation": ["percentage", {"severity": "warning"}],
        "custom-property-empty-line-before": null,
        "declaration-empty-line-before": null,
        "scss/at-extend-no-missing-placeholder": null,
        "scss/selector-no-redundant-nesting-selector": null,
        "scss/selector-no-union-class-name": null,
        "scss/no-global-function-names": null,
        "scss/dollar-variable-pattern": null,
        "scss/dollar-variable-empty-line-before": null,
        "scss/comment-no-empty": [true, { "severity": "warning" }],
        "comment-whitespace-inside": null,
        "scss/dollar-variable-colon-space-before": null,
        "scss/dollar-variable-colon-space-after": null,
        "scss/operator-no-unspaced": null,
        "scss/at-mixin-argumentless-call-parentheses": null,
        "scss/double-slash-comment-empty-line-before": null,
        "scss/double-slash-comment-whitespace-inside": null,
        "declaration-block-single-line-max-declarations": null,
        "block-no-redundant-nested-style-rules": null,
        "length-zero-no-unit": null,
        "declaration-block-no-redundant-longhand-properties": null,
        "rule-empty-line-before": null,
        "comment-empty-line-before": null,
        "syntax-string-no-invalid": null,
        "no-invalid-position-declaration": null,
        "color-hex-length": ["short", { "severity": "warning" }],
        "declaration-block-no-shorthand-property-overrides": null,
        "declaration-block-no-duplicate-properties": [true, { "severity": "warning" }],
        "color-function-alias-notation": null,
        "container-name-pattern": null,
        "declaration-property-value-keyword-no-deprecated": null,
        "value-keyword-case": null,
        "scss/operator-no-newline-after": null,
        "shorthand-property-no-redundant-values": null,
        "no-empty-source": null,
        "scss/load-no-partial-leading-underscore": null,
        "custom-property-pattern": null,
        "property-no-vendor-prefix": null,
        "property-no-unknown": [true, { "ignoreProperties": ["user-drag", "-webkit-user-drag"] }],
        "unit-allowed-list": [
            "em", "rem", "s", "ms", "px", "%",
            "dvi", "dvb", "dvh", "dvw", "svh", "svw",
            "lvh", "lvw", "cqi", "cqb", "cqw", "cqh",
            "deg", "rad", "grad", "turn", "fr",
            "cqmin", "cqmax"
        ],
        "logical-css/require-logical-properties": [true, {"severity": "warning"}],
        "logical-css/require-logical-units": [true, {"severity": "warning"}],
        "logical-css/require-logical-keywords": [true, {"severity": "warning"}],
        "max-nesting-depth": 6,
        "selector-max-compound-selectors": 6
    }
}
